name: PR Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ecommerce-stores-fastapi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependecies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test/test.py